### ISSUE TITLE
settings.yaml instead of env variables

### ISSUE THREAD

**Issue by chickahoona** [tiagoposse/psono-helm-chart#1]
Hi,

Sascha here from Psono. Just a few comments:

- Instead of constructing a settings.yaml you should use environment variables. All parameters can noramlly be passed through with the "PSONO_" prefix. For example EMAIL_FROM becomes PSONO_EMAIL_FROM
- Instead of dealing with a docker container for server, client and portal, you could use our "combo" image which has all components bundled in one. https://hub.docker.com/r/psono/psono-combo and the source code https://gitlab.com/psono/psono-combo/-/blob/master/Dockerfile

Btw there is a license info missing ;)

**Comment by tiagoposse** [comment]
I'll modify to use the env vars, that simplifies the use cases.
I took a look into the combo image previously but decided against it. The idea behind that being the possibility to choose which components get installed, as the user might want to install multiple instances of the server or the webclient and so on.

License has been added 👍

**Comment by tiagoposse** [comment]
Using PSONO_* environment is now the way to configure the chart with v0.2.0
